Resource1 :
  name : MvnBuildDiscoveryServerDockerImage
  imageName : docker.artifactory-unified.soleng-us.jfrog.team/discoveryserverdockerimage
Resource2 :
  name : BuildMavenDiscoveryServer_ProduceDockerImage_BuildInfo
  imageName : docker.artifactory-unified.soleng-us.jfrog.team/discoveryserverdockerimage
Resource3 :
  name : DiscoveryProjectGitRepo
  gitProvider : Github_SolEng
  path: jfrog/SolEngDemo
  branch : pet-clinic-project

Artifactory: ArtifactoryUnified
Pipelines:
  name: BuildMavenDiscoveryServer_ProduceDockerImage
GitRepo:
  name: DiscoveryProjectGitRepo
  path: Samples/pet-clinic-project/spring-petclinic-microservices/spring-petclinic-discovery-server
Step1 :
  name: mvn_bld_discovery_server
Step2 :
  name: convert_mvnbuild_dockerimage
  dockerFileLocation: Samples/pet-clinic-project/spring-petclinic-microservices/spring-petclinic-discovery-server
  dockerImageName: docker.artifactory-unified.soleng-us.jfrog.team/discoveryserverdockerimage
  outputResourceName: MvnBuildDiscoveryServerDockerImage
Step3 :
  name: push_discovery_server_docker_image
  outputResourceName : BuildMavenConfigServer_ProduceDockerImage_BuildInfo


